### PR TITLE
Make compatible with Django 1.8

### PR DESCRIPTION
**Pull request by fdintino**
In Django 1.8, `DiscoverRunner.option_list` is replaced with the classmethod `DiscoverRunner.add_arguments()`

### CODE REVIEW

**Comment by charettes** [comment]
Could someone consider merging this?

**Comment by fdintino** [comment]
Yes, is this project still being maintained? This is a very straightforward compatibility change (maintaining backwards compatibility) and without it the app does not run in django 1.8.

**Comment by charettes** [comment]
@camilonova, if you don't have time to work on this anymore I'd be glad to get the contributor rights and maintain it.

**Comment by camilonova** [comment]
@fdintino Thank you.

@charettes Thank you, please add yourself to jazzband and start right away. Welcome on board.

**Comment by charettes** [comment]
@camilonova just did, thanks!

**Comment by camilonova** [comment]
@charettes will be great if you take a look into automated tests and readthedocs, for sure the integrations are outdated.

**Comment by charettes** [comment]
Will try to have a look today.

**Pull request merged**
